### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by szarnyasg** [owensgroup/push-pull#3]
Hi,

I just stumbled upon this paper - great work. One thing I noticed is that a couple of links in the README are broken:
* pushpull-icpp18-final.pdf
* LICENSE.md
* Scott Beamer's Direction-optimization paper

Best,
Gabor

**Comment by ctcyang** [comment]
Hi Gabor,
Thank you for your kind words! I've fixed the links in the README.

Regards,
Carl
